### ISSUE TITLE
Module 4 Assignment

### ISSUE THREAD

**Issue by pattacini** [Campus-Advisors/campus-advisor-training-pattacini#10]
The post can be browsed at https://education.github.community/t/module-4-exercise-1-student-programs/26002/389?u=pattacini.

---

![Annotation 2019-12-30 171237](https://user-images.githubusercontent.com/3738070/71590135-a464a680-2b27-11ea-8007-acc6a8443c62.jpg)

**Comment by ericdrosado** [comment]
This is a fantastic writeup! Thanks for sharing!

**Comment by pattacini** [comment]
Thanks @ericdrosado!
Looking forward to the Campus Advisor interview!
